# -*- coding: utf-8 -*-

def nuevo(db):
    db.define_table('producto',
                Field('nroprod', type = 'id'),
                Field('preciocred',type = 'double'),
                Field('preciocont', type = 'double'),
                Field('descripcion',type = 'string', length=30),
                Field('volvta',type = 'double'),
                Field('facvta',type = 'double'),
                migrate=migrate, fake_migrate=fake_migrate
               )
    db.define_table('precio',
                Field('nrocambio', type = 'id'),
                Field('hora',type = 'datetime'),
                Field('newprice', type = 'double'),
                Field('combustible', db.producto, default=session.id),
                Field('on_line', type = 'boolean', default = False),
                Field('cemprod', type ='integer'),
                migrate=migrate, fake_migrate=fake_migrate
               )
    db.define_table('tanques',
                Field('nrotanque', type = 'id'),
                Field('volumen',type = 'double',unique = True),
                Field('combustible', db.producto, default=session.id),
                migrate=migrate, fake_migrate=fake_migrate
                )
    db.define_table('picos',
                Field('nropico', type = 'id'),
                Field('surtidor',type = 'integer', requires=IS_INT_IN_RANGE(1, 33)),
                Field('manguera',type = 'integer', requires=IS_INT_IN_RANGE(1, 5)),
                Field('tiposurtidor',type = 'string'),
                Field('tanque', db.tanques, default=session.id),
                Field('estado', type = 'string' , default = 'Fuera de Linea'),
                Field('nesta', type = 'integer', default = 0 ),
                Field('totalvolinicial', type = 'double',default =0),
                Field('totalvolfinal', type = 'double',default =0),
                Field('totalvoldif',type = 'double',default =0),
                migrate=migrate, fake_migrate=fake_migrate
                )
    db.define_table('tdespa',
                Field('pico', type = 'id'),
                Field('horainicio',default = request.now,requires=IS_DATETIME(str(T('%d-%m-%y %H:%M')))),
                Field('volinicial', type = 'double',default =0),
                Field('factinicial', type = 'double',default =0),
                Field('ml', type = 'integer',default =0),
                Field('mm', type = 'integer',default =0),
                migrate=migrate, fake_migrate=fake_migrate
                )
    db.define_table('turnos',
                Field('nroturno', type = 'id'),
                Field('inicio',type = 'datetime',default = request.now, requires=IS_DATETIME(str(T('%d-%m-%y %H:%M')))),
                Field('fin',type = 'datetime',default = request.now,requires=IS_DATETIME(str(T('%d-%m-%y %H:%M')))),
                Field('cerrado', 'boolean', default= False),
                Field('pico1volfinal', type = 'double',default =0 ),
                Field('pico2volfinal', type = 'double',default =0),
                Field('pico3volfinal', type = 'double',default =0),
                Field('pico4volfinal', type = 'double',default =0),
                Field('pico5volfinal', type = 'double',default =0),
                Field('pico6volfinal', type = 'double',default =0),
                Field('pico7volfinal', type = 'double',default =0),
                Field('pico8volfinal', type = 'double',default =0),
                Field('pico9volfinal', type = 'double',default =0),
                Field('pico10volfinal', type = 'double',default =0),
                Field('pico11volfinal', type = 'double',default =0),
                Field('pico12volfinal', type = 'double',default =0),
                Field('pico13volfinal', type = 'double',default =0),
                Field('pico14volfinal', type = 'double',default =0),
                Field('pico15volfinal', type = 'double',default =0),
                Field('pico16volfinal', type = 'double',default =0),
                Field('pico1vol', type = 'double',default =0),
                Field('pico2vol', type = 'double',default =0),
                Field('pico3vol', type = 'double',default =0),
                Field('pico4vol', type = 'double',default =0),
                Field('pico5vol', type = 'double',default =0),
                Field('pico6vol', type = 'double',default =0),
                Field('pico7vol', type = 'double',default =0),
                Field('pico8vol', type = 'double',default =0),
                Field('pico9vol', type = 'double',default =0),
                Field('pico10vol', type = 'double',default =0),
                Field('pico11vol', type = 'double',default =0),
                Field('pico12vol', type = 'double',default =0),
                Field('pico13vol', type = 'double',default =0),
                Field('pico14vol', type = 'double',default =0),
                Field('pico15vol', type = 'double',default =0),
                Field('pico16vol', type = 'double',default =0),
                Field('activo', type ='integer',default =0),
                migrate=migrate, fake_migrate=fake_migrate
               )
    db.define_table('despachos',
                Field('nrodesp', type = 'id'),
                Field('horainicio',type = 'datetime',default = request.now, requires=IS_DATE(str(T('%d-%m-%y %I:%m %p')))),
                Field('horafin',type = 'datetime',default = request.now,requires=IS_DATE(str(T('%d-%m-%y %I:%m %p')))),
                Field('volinicial',type = 'double'),
                Field('volfinal',type = 'double'),
                Field('factinicial',type = 'double'),
                Field('tipofact',type = 'string',default='C'),
                Field('pico',type = 'integer'),
                Field('factfinal',type = 'double'),
                Field('turno',db.turnos, default = session.id),
                Field('volvta',type = 'decimal(10,3)'),
                Field('facvta',type = 'decimal(10,2)'),
                Field('nrocem', type ='integer'),
                Field('pago', type ='string',default = '00'),
                migrate=migrate, fake_migrate=fake_migrate
                )

def viejo(db):
    db.define_table('producto',
                Field('nroprod', type = 'id'),
                Field('preciocred',type = 'double'),
                Field('preciocont', type = 'double'),
                Field('descripcion',type = 'string', length=30),
                Field('volvta',type = 'double'),
                Field('facvta',type = 'double'),
                migrate=migrate, fake_migrate=fake_migrate
               )
    db.define_table('precio',
                Field('nrocambio', type = 'id'),
                Field('hora',type = 'datetime'),
                Field('newprice', type = 'double'),
                Field('combustible', db.producto, default=session.id),
                Field('on_line', type = 'boolean', default = False),
                Field('cemprod', type ='integer'),
                migrate=migrate, fake_migrate=fake_migrate
               )
    db.define_table('tanques',
                Field('nrotanque', type = 'id'),
                Field('volumen',type = 'double',unique = True),
                Field('combustible', db.producto, default=session.id),
                migrate=migrate, fake_migrate=fake_migrate
                )
    db.define_table('picos',
                Field('nropico', type = 'id'),
                Field('surtidor',type = 'integer', requires=IS_INT_IN_RANGE(1, 33)),
                Field('manguera',type = 'integer', requires=IS_INT_IN_RANGE(1, 5)),
                Field('tiposurtidor',type = 'string'),
                Field('tanque', db.tanques, default=session.id),
                Field('estado', type = 'string' , default = 'Fuera de Linea'),
                Field('nesta', type = 'integer', default = 0 ),
                Field('totalvolinicial', type = 'double',default =0),
                Field('totalvolfinal', type = 'double',default =0),
                Field('totalvoldif',type = 'double',default =0),
                migrate=migrate, fake_migrate=fake_migrate
                )
    db.define_table('tdespa',
                Field('pico', type = 'id'),
                Field('horainicio',default = request.now,requires=IS_DATETIME(str(T('%d-%m-%y %H:%M')))),
                Field('volinicial', type = 'double',default =0),
                Field('factinicial', type = 'double',default =0),
                Field('ml', type = 'integer',default =0),
                Field('mm', type = 'integer',default =0),
                migrate=migrate, fake_migrate=fake_migrate
                )
    db.define_table('turnos',
                Field('nroturno', type = 'id'),
                Field('inicio',type = 'datetime',default = request.now, requires=IS_DATETIME(str(T('%d-%m-%y %H:%M')))),
                Field('fin',type = 'datetime',default = request.now,requires=IS_DATETIME(str(T('%d-%m-%y %H:%M')))),
                Field('cerrado', 'boolean', default= False),
                Field('pico1volfinal', type = 'double',default =0 ),
                Field('pico2volfinal', type = 'double',default =0),
                Field('pico3volfinal', type = 'double',default =0),
                Field('pico4volfinal', type = 'double',default =0),
                Field('pico5volfinal', type = 'double',default =0),
                Field('pico6volfinal', type = 'double',default =0),
                Field('pico7volfinal', type = 'double',default =0),
                Field('pico8volfinal', type = 'double',default =0),
                Field('pico9volfinal', type = 'double',default =0),
                Field('pico10volfinal', type = 'double',default =0),
                Field('pico11volfinal', type = 'double',default =0),
                Field('pico12volfinal', type = 'double',default =0),
                Field('pico13volfinal', type = 'double',default =0),
                Field('pico14volfinal', type = 'double',default =0),
                Field('pico15volfinal', type = 'double',default =0),
                Field('pico16volfinal', type = 'double',default =0),
                Field('pico1vol', type = 'double',default =0),
                Field('pico2vol', type = 'double',default =0),
                Field('pico3vol', type = 'double',default =0),
                Field('pico4vol', type = 'double',default =0),
                Field('pico5vol', type = 'double',default =0),
                Field('pico6vol', type = 'double',default =0),
                Field('pico7vol', type = 'double',default =0),
                Field('pico8vol', type = 'double',default =0),
                Field('pico9vol', type = 'double',default =0),
                Field('pico10vol', type = 'double',default =0),
                Field('pico11vol', type = 'double',default =0),
                Field('pico12vol', type = 'double',default =0),
                Field('pico13vol', type = 'double',default =0),
                Field('pico14vol', type = 'double',default =0),
                Field('pico15vol', type = 'double',default =0),
                Field('pico16vol', type = 'double',default =0),
                Field('activo', type ='integer',default =0),
                migrate=migrate, fake_migrate=fake_migrate
               )
    db.define_table('despachos',
                Field('nrodesp', type = 'id'),
                Field('horainicio',type = 'datetime',default = request.now, requires=IS_DATE(str(T('%d-%m-%y %I:%m %p')))),
                Field('horafin',type = 'datetime',default = request.now,requires=IS_DATE(str(T('%d-%m-%y %I:%m %p')))),
                Field('volinicial',type = 'double'),
                Field('volfinal',type = 'double'),
                Field('factinicial',type = 'double'),
                Field('tipofact',type = 'string',default='C'),
                Field('pico',type = 'integer'),
                Field('factfinal',type = 'double'),
                Field('turno',db.turnos, default = session.id),
                Field('volvta',type = 'decimal(10,3)'),
                Field('facvta',type = 'decimal(10,2)'),
                Field('nrocem', type ='integer'),
                Field('pago', type ='string',default = '00'),
                migrate=migrate, fake_migrate=fake_migrate
                )
